package com.paydaytracker.app.ui.parity

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import com.paydaytracker.app.data.*
import com.paydaytracker.app.ui.MainViewModel
import com.paydaytracker.app.ui.common.Formatters as F
import org.json.JSONObject
import java.time.*
import java.util.UUID

@Composable fun categoryName(id:String,categories:List<CustomCategory>):String = categories.firstOrNull{it.id==id}?.name ?: when(id){"rent"->L("Rent","Miete");"utilities"->L("Utilities","Nebenkosten");"health"->L("Health insurance","Krankenversicherung");"groceries"->L("Groceries","Lebensmittel");"transport"->L("Transport","Transport");else->L("Other","Sonstiges")}
@Composable fun Expenses(vm:MainViewModel) {
    val all by vm.expenses.collectAsState();val recurring by vm.recurringExpenses.collectAsState();val month by vm.selectedMonth.collectAsState();val settings by vm.settings.collectAsState();val categories by vm.customCategories.collectAsState();val shifts by vm.shifts.collectAsState();val places by vm.workplaces.collectAsState()
    val list=all.filter{it.date.startsWith(month)};val total=list.sumOf{it.amount};val net=PayrollCalculator.summary(month,shifts,settings,places,"all").est.net
    var open by remember{mutableStateOf(false)};var editing by remember{mutableStateOf<Expense?>(null)};var deleting by remember{mutableStateOf<Expense?>(null)}
    Page {
        Action(L("+ Add expense","+ Ausgabe hinzufügen"),primary=true){editing=null;open=true}
        WageCard{Eyebrow(L("Expenses this month","Ausgaben dieses Monats"));Text(F.formatMoney(total,settings.currency),fontSize=30.sp,fontWeight=FontWeight.Bold);Text("${list.size} "+L("expenses","Ausgaben"),fontSize=13.sp)}
        WageCard{Eyebrow(L("Available after expenses","Nach Ausgaben verfügbar"));Text(F.formatMoney(net-total,settings.currency),fontSize=30.sp,fontWeight=FontWeight.Bold);Text(L("Estimated net minus expenses","Geschätztes Netto minus Ausgaben"),fontSize=12.sp)}
        WageCard{Eyebrow(L("Savings target","Sparziel"));Text((if(settings.savingsTarget>0)((net-total).coerceAtLeast(0.0)/settings.savingsTarget*100).coerceAtMost(100.0).toInt()else 0).toString()+"%",fontSize=30.sp);Text(L("Target: ","Ziel: ")+F.formatMoney(settings.savingsTarget,settings.currency),fontSize=12.sp)}
        WageCard{Heading(L("Your expenses","Deine Ausgaben"));if(list.isEmpty())Text(L("No expenses yet.","Noch keine Ausgaben."));list.sortedByDescending{it.date}.forEach{e->Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f).clickable{editing=e;open=true}.padding(vertical=12.dp)){Text(categoryName(e.category,categories),fontWeight=FontWeight.SemiBold);Text(e.date+if(e.note.isNullOrBlank())""else " · "+e.note,fontSize=11.sp);Text(F.formatMoney(e.amount,settings.currency),fontSize=16.sp)};TextButton({editing=e;open=true}){Text(L("Edit","Bearbeiten"),fontSize=11.sp)};IconButton({deleting=e}){Text("×",fontSize=22.sp)}};HorizontalDivider()}}
        if(recurring.isNotEmpty())WageCard{Heading(L("Recurring expenses","Wiederkehrende Ausgaben"));recurring.forEach{r->LinkRow(categoryName(r.category,categories),F.formatMoney(r.amount,settings.currency)+L(" · monthly"," · monatlich")){editing=list.firstOrNull{it.recurringId==r.id} ?: Expense(UUID.randomUUID().toString(),month+"-%02d".format(r.day.coerceAtMost(YearMonth.parse(month).lengthOfMonth())),r.amount,r.category,r.note,r.id);open=true}}}
    }
    if(open)ExpenseEditor(vm,editing,{open=false})
    if(deleting!=null)AlertDialog(onDismissRequest={deleting=null},title={Text(if(deleting!!.recurringId!=null)L("Delete this and future recurring expenses?","Diese und künftige wiederkehrende Ausgaben löschen?")else L("Delete expense?","Ausgabe löschen?"))},confirmButton={TextButton({vm.deleteExpense(deleting!!.id);deleting=null}){Text(L("Delete","Löschen"))}},dismissButton={TextButton({deleting=null}){Text(L("Cancel","Abbrechen"))}})
}
@Composable fun ExpenseEditor(vm:MainViewModel,expense:Expense?,dismiss:()->Unit) {
    val categories by vm.customCategories.collectAsState();val month by vm.selectedMonth.collectAsState();val settings by vm.settings.collectAsState()
    var date by remember{mutableStateOf(expense?.date ?: if(LocalDate.now().toString().startsWith(month))LocalDate.now().toString()else month+"-01")};var amount by remember{mutableStateOf(expense?.amount?.toString() ?: "")};var category by remember{mutableStateOf(expense?.category ?: "other")};var note by remember{mutableStateOf(expense?.note ?: "")};var repeat by remember{mutableStateOf(expense?.recurringId!=null)};var newCategory by remember{mutableStateOf("")};var error by remember{mutableStateOf(false)}
    AlertDialog(onDismissRequest=dismiss,title={Text(L("Expense","Ausgabe"))},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){Field(L("Date (YYYY-MM-DD)","Datum (JJJJ-MM-TT)"),date,{date=it});Field(L("Amount","Betrag")+" (${settings.currency})",amount,{amount=it});Choice(L("Category","Kategorie"),category,(listOf("rent","utilities","health","groceries","transport","other")+categories.map{it.id}).map{it to categoryName(it,categories)}){category=it};Field(L("Note (optional)","Notiz (optional)"),note,{note=it});Toggle(L("Recurring monthly","Monatlich wiederholen"),checked=repeat){repeat=it};Field(L("New category","Neue Kategorie"),newCategory,{newCategory=it});Action(L("Add category","Kategorie hinzufügen"),enabled=newCategory.isNotBlank()){val c=CustomCategory(UUID.randomUUID().toString(),newCategory.trim());vm.saveCustomCategory(c);category=c.id;newCategory=""};if(error)Text(L("Enter a valid date and amount.","Gültiges Datum und Betrag eingeben."),color=MaterialTheme.colorScheme.error)}},confirmButton={TextButton({val money=amount.replace(',','.').toDoubleOrNull();val day=runCatching{LocalDate.parse(date)}.getOrNull();if(day==null||money==null||!money.isFinite()||money<=0)error=true else {val rid=if(repeat)expense?.recurringId ?: UUID.randomUUID().toString()else null;vm.saveExpense(Expense(expense?.id ?: UUID.randomUUID().toString(),date,money,category,note,rid));if(rid!=null)vm.saveRecurringExpense(RecurringExpense(rid,date.take(7),day.dayOfMonth,money,category,note));else expense?.recurringId?.let{vm.deleteRecurring(it)};dismiss()}}){Text(L("Save expense","Ausgabe speichern"))}},dismissButton={TextButton(dismiss){Text(L("Cancel","Abbrechen"))}})
}
@Composable fun Planning(vm:MainViewModel) {
    val goals by vm.savingsGoals.collectAsState();val settings by vm.settings.collectAsState();val month by vm.selectedMonth.collectAsState();val document by vm.document.collectAsState();val projection by vm.currentSpendingProjection.collectAsState();val categories by vm.customCategories.collectAsState();val expenses by vm.expenses.collectAsState();val available by vm.savingsAvailableCents.collectAsState()
    val budgets=JSONObject(document).optJSONObject("budgets") ?: JSONObject();val budget=budgets.optJSONObject(month) ?: JSONObject()
    var editing by remember{mutableStateOf<SavingsGoal?>(null)};var open by remember{mutableStateOf(false)};var contribution by remember{mutableStateOf<SavingsGoal?>(null)};var deleting by remember{mutableStateOf<SavingsGoal?>(null)};var total by remember(month,document){mutableStateOf(budget.optDouble("total",0.0).toString())}
    Page{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Heading(L("Savings goals","Sparziele"));Action(L("+ Goal","+ Sparziel"),primary=true){editing=null;open=true}}
        goals.forEach{g->WageCard{Row(horizontalArrangement=Arrangement.spacedBy(16.dp),verticalAlignment=Alignment.CenterVertically){val p=if(g.target>0)(g.saved/g.target).toFloat().coerceIn(0f,1f)else 0f;Box(Modifier.size(72.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(progress={p},Modifier.fillMaxSize(),color=Pink,strokeWidth=7.dp,trackColor=Color(0xFFE6DDEE));Text("${(p*100).toInt()}%",fontSize=21.sp,fontWeight=FontWeight.Bold)};Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(if(g.defaultName)L("My savings goal","Mein Sparziel")else g.name,fontSize=19.sp,fontWeight=FontWeight.SemiBold);Text(F.formatMoney(g.saved,settings.currency)+" / "+F.formatMoney(g.target,settings.currency),fontSize=12.sp);Text(L("Remaining: ","Verbleibend: ")+F.formatMoney((g.target-g.saved).coerceAtLeast(0.0),settings.currency),fontSize=11.sp)}}
            if(g.auto)Text(L("Next contribution: ","Nächster Beitrag: ")+g.autoNext,fontSize=11.sp)
            Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Action(L("Edit","Bearbeiten")){editing=g;open=true};Action(L("+ Add money","+ Geld hinzufügen")){contribution=g}}
            TextButton({deleting=g}){Text(L("Delete goal","Sparziel löschen"),fontSize=12.sp)}
        }}
        WageCard{Eyebrow(L("Available for savings","Zum Sparen verfügbar"));Heading(F.formatMoney(available/100.0,settings.currency))}
        WageCard{Heading(L("Monthly budget","Monatsbudget"));Field(L("Total limit","Gesamtlimit")+" (${settings.currency})",total,{total=it});Action(L("Save budget","Budget speichern"),primary=true,enabled=total.replace(',','.').toDoubleOrNull()?.let{it.isFinite()&&it>=0}==true){vm.updateDocument{d->val b=d.optJSONObject("budgets") ?: JSONObject();b.put(month,(b.optJSONObject(month) ?: JSONObject()).put("total",total.replace(',','.').toDouble()));d.put("budgets",b)}};Stat(L("Spent","Ausgegeben"),F.formatMoney(projection?.spent ?: 0.0,settings.currency));Stat(L("Projected","Prognose"),F.formatMoney(projection?.projected ?: 0.0,settings.currency))
            Stat(L("Remaining budget","Verbleibendes Budget"),F.formatMoney(budget.optDouble("total",0.0)-(projection?.logged ?: 0.0),settings.currency))
            Text(L("Category limits are part of the total budget. 0 means no limit.","Kategorielimits sind Teil des Gesamtbudgets. 0 bedeutet kein Limit."),fontSize=11.sp)
            (listOf("rent","utilities","health","groceries","transport","other")+categories.map{it.id}).forEach { id ->
                var limit by remember(month,id,document) { mutableStateOf(budget.optDouble(id,0.0).toString()) }
                Field(categoryName(id,categories),limit,{limit=it})
                val n=limit.replace(',','.').toDoubleOrNull()
                Row(verticalAlignment=Alignment.CenterVertically) {
                    Text(F.formatMoney(expenses.filter{it.date.startsWith(month)&&it.category==id}.sumOf{it.amount},settings.currency),Modifier.weight(1f),fontSize=12.sp)
                    TextButton({vm.updateDocument{d->val b=d.optJSONObject("budgets") ?: JSONObject();b.put(month,(b.optJSONObject(month) ?: JSONObject()).put(id,n));d.put("budgets",b)}},enabled=n!=null&&n.isFinite()&&n>=0){Text(L("Save limit","Limit speichern"))}
                }
            }
        }
    }
    if(open)GoalEditor(vm,editing,{open=false})
    contribution?.let{g->var amount by remember{mutableStateOf("")};val n=amount.replace(',','.').toDoubleOrNull();AlertDialog(onDismissRequest={contribution=null},title={Text(L("Add money","Geld hinzufügen"))},text={Field(settings.currency,amount,{amount=it})},confirmButton={TextButton({if(n!=null&&n.isFinite()&&n>0){vm.saveSavingsGoal(g.copy(saved=g.saved+n));contribution=null}},enabled=n!=null&&n.isFinite()&&n>0){Text(L("Save","Speichern"))}},dismissButton={TextButton({contribution=null}){Text(L("Cancel","Abbrechen"))}})}
    deleting?.let{g->AlertDialog(onDismissRequest={deleting=null},title={Text(L("Delete savings goal?","Sparziel löschen?"))},confirmButton={TextButton({vm.deleteSavingsGoal(g.id);deleting=null}){Text(L("Delete","Löschen"))}},dismissButton={TextButton({deleting=null}){Text(L("Cancel","Abbrechen"))}})}
}
@Composable fun GoalEditor(vm:MainViewModel,goal:SavingsGoal?,dismiss:()->Unit) {
    val settings by vm.settings.collectAsState();var name by remember{mutableStateOf(goal?.name ?: "")};var target by remember{mutableStateOf(goal?.target?.toString() ?: "500")};var saved by remember{mutableStateOf(goal?.saved?.toString() ?: "0")};var auto by remember{mutableStateOf(goal?.auto ?: false)};var amount by remember{mutableStateOf(goal?.autoAmount?.toString() ?: "50")};var interval by remember{mutableStateOf(goal?.autoInterval ?: "monthly")};var next by remember{mutableStateOf(goal?.autoNext?.takeIf{it.isNotEmpty()} ?: LocalDate.now().plusMonths(1).toString())};var due by remember{mutableStateOf(goal?.due ?: "")};var error by remember{mutableStateOf(false)}
    AlertDialog(onDismissRequest=dismiss,title={Text(L("Savings goal","Sparziel"))},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){Field(L("Name","Name"),name,{name=it});Field(L("Target","Ziel")+" (${settings.currency})",target,{target=it});Field(L("Saved","Gespart"),saved,{saved=it});Field(L("Due date (optional)","Zieldatum (optional)"),due,{due=it});Toggle(L("Automatic contributions","Automatische Beiträge"),checked=auto){auto=it};if(auto){Field(L("Amount","Betrag"),amount,{amount=it});Choice(L("Repeat","Wiederholen"),interval,listOf("weekly" to L("Weekly","Wöchentlich"),"monthly" to L("Monthly","Monatlich"),"yearly" to L("Yearly","Jährlich"))){interval=it};Field(L("Next date (YYYY-MM-DD)","Nächstes Datum (JJJJ-MM-TT)"),next,{next=it})};if(error)Text(L("Check the amounts and dates.","Beträge und Daten prüfen."),color=MaterialTheme.colorScheme.error)}},confirmButton={TextButton({val t=target.replace(',','.').toDoubleOrNull();val s=saved.replace(',','.').toDoubleOrNull();val a=amount.replace(',','.').toDoubleOrNull();val date=runCatching{LocalDate.parse(next)}.getOrNull();if(name.isBlank()||t==null||!t.isFinite()||t<=0||s==null||!s.isFinite()||s<0||auto&&(a==null||!a.isFinite()||a<=0||date==null)||due.isNotEmpty()&&runCatching{LocalDate.parse(due)}.isFailure)error=true else {vm.saveSavingsGoal((goal ?: SavingsGoal(UUID.randomUUID().toString(),name,t)).copy(name=name,target=t,saved=s,due=due,auto=auto,autoAmount=a ?: 0.0,autoInterval=interval,autoNext=if(auto)next else "",autoAnchor=date?.dayOfMonth ?: 1,autoEpoch=goal?.autoEpoch ?: UUID.randomUUID().toString()));dismiss()}}){Text(L("Save","Speichern"))}},dismissButton={TextButton(dismiss){Text(L("Cancel","Abbrechen"))}})
}
@Composable fun History(vm:MainViewModel,manage:()->Unit) {
    val month by vm.selectedMonth.collectAsState();val shifts by vm.shifts.collectAsState();val settings by vm.settings.collectAsState();val places by vm.workplaces.collectAsState();val filter by vm.workplaceFilter.collectAsState();val payslips by vm.payslips.collectAsState();var open by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<Payslip?>(null)}
    Page{WorkplacePicker(vm,manage);WageCard{Heading(L("Payslip comparison","Lohnvergleich"));Action(L("+ Add payslip","+ Abrechnung hinzufügen"),primary=true){edit=null;open=true};payslips.filter{it.month==month&&(filter=="all"||it.workplaceId==filter)}.forEach{p->val expected=PayrollCalculator.summary(month,shifts,settings,places,p.workplaceId);LinkRow(places.firstOrNull{it.id==p.workplaceId}?.name ?: p.month,F.formatMoney(p.actualNet,settings.currency)){edit=p;open=true};Stat(L("Estimated net","Geschätztes Netto"),F.formatMoney(expected.est.net,settings.currency));Stat(L("Difference","Differenz"),F.formatMoney(p.actualNet-expected.est.net,settings.currency))}}
        PayTrend(payslips,shifts,settings,places,filter)
        repeat(6){i->val m=YearMonth.parse(month).minusMonths(i.toLong()).toString();val s=PayrollCalculator.summary(m,shifts,settings,places,filter,includePlanned=false);WageCard{Eyebrow(if(i==0)L("Selected","Ausgewählt")else L("Monthly archive","Monatsarchiv"));Heading(F.formatMonthTitle(m));Text(F.formatMoney(s.gross,settings.currency),fontSize=30.sp,fontWeight=FontWeight.Bold);Stat(L("Bonuses","Zuschläge"),F.formatMoney(s.bonus.total,settings.currency));Stat(L("Estimated net","Geschätztes Netto"),F.formatMoney(s.est.net,settings.currency));Stat(L("Working time","Arbeitszeit"),F.formatDuration(s.minutes));Stat(L("Shifts","Schichten"),s.done.size.toString())}}
    }
    if(open){var wp by remember{mutableStateOf(edit?.workplaceId ?: places.firstOrNull()?.id ?: "")};var gross by remember{mutableStateOf(edit?.actualGross?.toString() ?: "")};var net by remember{mutableStateOf(edit?.actualNet?.toString() ?: "")};var error by remember{mutableStateOf(false)};AlertDialog(onDismissRequest={open=false},title={Text(L("Payslip","Lohnabrechnung")+" · "+month)},text={Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Choice(L("Workplace","Arbeitsplatz"),wp,places.map{it.id to it.name}){wp=it};Field(L("Actual gross","Tatsächliches Brutto"),gross,{gross=it});Field(L("Actual net","Tatsächliches Netto"),net,{net=it});if(error)Text(L("Enter valid amounts.","Gültige Beträge eingeben."))}},confirmButton={TextButton({val g=gross.replace(',','.').toDoubleOrNull();val n=net.replace(',','.').toDoubleOrNull();if(wp.isEmpty()||g==null||n==null||!g.isFinite()||!n.isFinite()||g<0||n<0)error=true else {vm.savePayslip(Payslip(edit?.id ?: payslips.firstOrNull{it.month==month&&it.workplaceId==wp}?.id ?: UUID.randomUUID().toString(),month,wp,g,n));open=false}}){Text(L("Save","Speichern"))}},dismissButton={Row{if(edit!=null)TextButton({vm.deletePayslip(edit!!.id);open=false}){Text(L("Delete","Löschen"))};TextButton({open=false}){Text(L("Cancel","Abbrechen"))}}})}
}
